name       : gnote
version    : 3.28.0
release    : 6
source     :
    - https://download.gnome.org/sources/gnote/3.28/gnote-3.28.0.tar.xz : a50d3986c6cc04c7c8215dfed938910611e2d7499f00bfe4f42050ed56a7b783
license    : GPL-3.0-or-later
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
