name       : gnote
version    : 3.34.1
release    : 11
source     :
    - https://download.gnome.org/sources/gnote/3.34/gnote-3.34.1.tar.xz : 4f41c49265376d9e9fd8fcb43e13779c1f965411c67969d18b0e12878d70c3cb
license    : GPL-3.0-or-later
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
