name       : gnote
version    : 3.20.2
release    : 2
source     :
    - http://ftp.gnome.org/pub/GNOME/sources/gnote/3.20/gnote-3.20.2.tar.xz : fdc76ae31dc8925545806c1702cf74e1c8f387b16519ed995987194f688555eb
license    : GPL-3.0
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
