name       : gnote
version    : '40.0'
release    : 17
source     :
    - https://download.gnome.org/sources/gnote/40/gnote-40.0.tar.xz : e224caf8bb433dec9a2258ea2f8739afabde577210e7fb17596614569f7d0b3b
license    : GPL-3.0-or-later
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
