name       : gnote
version    : 3.26.0
release    : 5
source     :
    - https://download.gnome.org/sources/gnote/3.26/gnote-3.26.0.tar.xz : de205ace226a010aba576654db6a8e06eab064522549d3bdd6eb8a0bc9163be9
license    : GPL-3.0
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
