name       : gnote
version    : 3.38.1
release    : 16
source     :
    - https://download.gnome.org/sources/gnote/3.38/gnote-3.38.1.tar.xz : c427d5e177339106e53976ab4f65f8719a48f7f712ce94d2184d545da174b2a9
license    : GPL-3.0-or-later
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
