name       : gnote
version    : 3.22.1
release    : 3
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnote/3.22/gnote-3.22.1.tar.xz : fa9434c2ba11bea73bd63436e5fd76949aca4f66dfd902295629c66ef27cd5eb
license    : GPL-3.0
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
