name       : gnote
version    : '44.0'
release    : 24
source     :
    - https://download.gnome.org/sources/gnote/44/gnote-44.0.tar.xz : dc3bd79268fe99d4ed56679ac076cc9d9aaaf62796138d371cf08815f7e6492d
homepage   : https://wiki.gnome.org/Apps/Gnote
license    : GPL-3.0-or-later
component  : office.notes
summary    : A simple and easy to use desktop note-taking application
description: |
    Gnote is a simple note-taking application for GNOME desktop environment. It allows you to capture your ideas, link them together using WikiWiki-style links, group together in notebooks and some extra features for everyday use. 
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
