name       : gnote
version    : '41.0'
release    : 19
source     :
    - https://download.gnome.org/sources/gnote/41/gnote-41.0.tar.xz : ffd1aed8a332a6031800590b914433445bc582e435abbef1d771e210143a3200
license    : GPL-3.0-or-later
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
