name       : gnote
version    : 3.36.2
release    : 14
source     :
    - https://download.gnome.org/sources/gnote/3.36/gnote-3.36.2.tar.xz : a4b438be86ecf944d5cc8de3e104955ca7f45663b154a547064fbcfc07c94522
license    : GPL-3.0-or-later
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
