name       : gnote
version    : 3.38.0
release    : 15
source     :
    - https://download.gnome.org/sources/gnote/3.38/gnote-3.38.0.tar.xz : fd36351f5fc8b4bf2e3a53d7d39798e0a33f0fc77ff781809577a346b85acfc6
license    : GPL-3.0-or-later
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gspell-1)
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
