name       : gnote
version    : 3.32.1
release    : 7
source     :
    - https://download.gnome.org/sources/gnote/3.32/gnote-3.32.1.tar.xz : b8c35188ab45409e3dbb153ac27ecb1029a344dcefff49d3cac4d9fa4c243366
license    : GPL-3.0-or-later
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
