name       : gnote
version    : 3.24.0
release    : 4
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnote/3.24/gnote-3.24.0.tar.xz : 62e38c19ce7dfcd895729adabd72f654f31e03f28dbf4cbca68279e745c79cd4
license    : GPL-3.0
component  : office.notes
summary    : Gnote started as a C++ port of Tomboy and has moved its own path later.
description: |
    Gnote started as a C++ port of Tomboy and has moved its own path later.
builddeps  :
    - pkgconfig(gtkmm-3.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libxslt)
    - desktop-file-utils
    - itstool
    - libboost-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
